### ISSUE TITLE
Include files not working

### ISSUE THREAD

**Issue by SockGuy** [cubedparadox/Cubeds-Unity-Shaders#38]
It says "failed to open source file : "Flatlittooncore.cginc" etc.
![not finding it](https://user-images.githubusercontent.com/36942342/36824528-17cb2b26-1cc0-11e8-852f-58855cd05966.jpg)

Is there anyway to fix this, thank you and I appreciate the work.

**Comment by netri** [comment]
1) Is it possible you've copied over only the .shader files (without .cginc files) ?
2) Try to reimport the .cginc files, that fixed similar issues for me in the past.
![image](https://user-images.githubusercontent.com/33671436/36916650-dd6a4336-1e54-11e8-959e-3c09af33103a.png)

**Comment by Slangnes** [comment]
The way I fixed it was I searched for the the missing files, 

[FlatLitToonCore.txt](https://github.com/cubedparadox/Cubeds-Unity-Shaders/files/1779735/FlatLitToonCore.txt)
[FlatLitToonShadows.txt](https://github.com/cubedparadox/Cubeds-Unity-Shaders/files/1779736/FlatLitToonShadows.txt)

Renamed the txt a cginc and it worked perfect.

**Comment by TCL987** [comment]
@SockGuy Is this still broken in version 0.25?

**Comment by SockGuy** [comment]
Nope. All is fixed. Thanks for your help

**Comment by SylveonBottle** [comment]
This has become an issue once again in 0.26.

![image](https://user-images.githubusercontent.com/17802843/48982123-a5651200-f0a3-11e8-9ce4-dfe3a2c5608d.png)

Re-importing doesn't fix.
